### ISSUE TITLE
not run with get started or cloning kunafa-todo

### ISSUE THREAD

**Issue by guibbv2011** [Kabbura/Kunafa#12]
Hello, it seems to be a lot of fun to use kunafa, but I can’t run following get started, or even cloning kunafa-todo… please make sure the step is right or kunafa-todo will run successfully

**Comment by Kabbura** [comment]
Hi,
Yeah the kunafa-todo repository wasn't updated in a while, but now it's been updated to the latest Kunafa version (v0.2.15) and Kotlin version and Kotlin Gradle plugin. 
Try to clone it and run `./gradlew run -t` and let me know if it works for you. 
The Docs are not yet updated however, but will be updated soon. 
Cheers.
