### ISSUE TITLE
Redirect doesn't pass URL params

### ISSUE THREAD

**Issue by hindabdo** [Kabbura/Kunafa#13]
If you have an `/path/<some id>/` and I need it to redirect to `/path/<some id>/dashboard` , the `redirect` function redirects to `/path/:id/dashboard` instead of the actual id.
### Expected behavior: 
The `redirect` function should redirect to  `/path/<some id>/dashboard`

**Comment by Kabbura** [comment]
Yeah you are right. I just pushed a new release `0.2.17` to fix this issue. 
Please check and let me know if it works.
