### ISSUE TITLE
Trouble in implementing Hello Kunafa example

### ISSUE THREAD

**Issue by sangeetds** [Kabbura/Kunafa#16]
Hi. I'm currently trying to implement this framework by following your Hello Kunafa tutorial. I think I've been able to sync the gradle properly and build the project. But I don't see anything when I open the index.html file. 
I've followed the instructions and modified the build.gradle and created index and app.kt. The build shows  successful but I can't see anything when I open the html file.(I'm using gradle build, also tried gradle assembleWeb and gradle compileK2J). Is there anything else in the 'Hello Kunafa' tutorial that I need to do?

**Comment by Kabbura** [comment]
Hi,
Can you post your build.gradle file and your index.html?

**Comment by sangeetds** [comment]
Hello. 
build.gradle:
`buildscript {
    ext.kotlin_version = '1.3.72'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
    }
}

group 'com.narbse'
version '1.0-SNAPSHOT'

apply plugin: 'kotlin2js'

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-js"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-js: 1.3.72"
    compile 'com.narbase:kunafa:0.2.0-beta'
    implementation 'com.narbase:kunafa:0.2.0-beta'
}

task assembleWeb(type: Sync) {
    configurations.compile.each { File file ->
        from(zipTree(file.absolutePath), {
            includeEmptyDirs = false
            include { fileTreeElement ->
                def path = fileTreeElement.path
                path.endsWith(".js") && (path.startsWith("META-INF/resources/") ||
                        !path.startsWith("META-INF/"))
            }
        })
    }
    from compileKotlin2Js.destinationDir
    into "${projectDir}/web"

    dependsOn classes
}

assemble.dependsOn assembleWeb

compileKotlin2Js {
    kotlinOptions.outputFile = "${projectDir}/web/output.js"
    kotlinOptions.moduleKind = "plain"
    kotlinOptions.sourceMap = true
}`

index.html:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kunemo demo</title>
</head>
<body>
    <script type="text/javascript" src="web/kotlin.js"></script>
    <script type="text/javascript" src="web/kunafa.js"></script>
    <script type="text/javascript" src="web/output.js"></script>
</body>
</html>`

**Comment by sangeetds** [comment]
Hello. Here it is:
build.gradle:
``<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kunemo demo</title>
</head>
<body>
    <script type="text/javascript" src="web/kotlin.js"></script>
    <script type="text/javascript" src="web/kunafa.js"></script>
    <script type="text/javascript" src="web/output.js"></script>
</body>
</html>``

**Comment by sangeetds** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kunemo demo</title>
</head>
<body>
    <script type="text/javascript" src="web/kotlin.js"></script>
    <script type="text/javascript" src="web/kunafa.js"></script>
    <script type="text/javascript" src="web/output.js"></script>
</body>
</html>`

**Comment by sangeetds** [comment]
Here it is:
index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kunemo demo</title>
</head>
<body>
    <script type="text/javascript" src="web/kotlin.js"></script>
    <script type="text/javascript" src="web/kunafa.js"></script>
    <script type="text/javascript" src="web/output.js"></script>
</body>
</html>
```

build.gradle:
```
buildscript {
    ext.kotlin_version = '1.3.72'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
    }
}

group 'com.narbse'
version '1.0-SNAPSHOT'

apply plugin: 'kotlin2js'

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-js"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-js: 1.3.72"
    compile 'com.narbase:kunafa:0.2.0-beta'
    implementation 'com.narbase:kunafa:0.2.0-beta'
}

task assembleWeb(type: Sync) {
    configurations.compile.each { File file ->
        from(zipTree(file.absolutePath), {
            includeEmptyDirs = false
            include { fileTreeElement ->
                def path = fileTreeElement.path
                path.endsWith(".js") && (path.startsWith("META-INF/resources/") ||
                        !path.startsWith("META-INF/"))
            }
        })
    }
    from compileKotlin2Js.destinationDir
    into "${projectDir}/web"

    dependsOn classes
}

assemble.dependsOn assembleWeb

compileKotlin2Js {
    kotlinOptions.outputFile = "${projectDir}/web/output.js"
    kotlinOptions.moduleKind = "plain"
    kotlinOptions.sourceMap = true
}
```

**Comment by Kabbura** [comment]
I think the Hello Kunafa tutorial has not been updated to use the new KotlinJs plugin (instead of `compileKotlin2Js`). 
To use the new plugin, check this [Kunafa Todo](https://github.com/Kabbura/kunafa-todo)
This is [build.gradle](https://github.com/Kabbura/kunafa-todo/blob/master/build.gradle) and this is the [index.html](https://github.com/Kabbura/kunafa-todo/blob/master/src/main/resources/index.html).
 We will update the Hello Kunafa tutorial shortly.

**Comment by sangeetds** [comment]
What command do you use to get your index.html running? 
I've tried using 
`gradle build`
and then opening the index.html 
Nothing happens.

**Comment by Kabbura** [comment]
try `./gradlew run -t` 
The `-t` is for continuous build

**Comment by sangeetds** [comment]
I'd tried that and I got this error : 
`Cannot GET / `

**Comment by Kabbura** [comment]
Interesting.. 
Can you try to clone the todo app and run `./gradlew run -t` and let me know if it works?

**Comment by sangeetds** [comment]
Tried that too, unfortunately it isn't working. I think I may be missing something I don't know. I will try once again and let you know

**Comment by Kabbura** [comment]
That's really strange.
What version of gradle are you using?

**Comment by Kabbura** [comment]
I added the gradle wrapper files to the Todo repo. It's using gradle-6.2-all.zip.
Try to clone it again and run it. I think it should work.

**Comment by sangeetds** [comment]
Thanks. I'll clean everything and start from scratch again. I'm using Gradle 6.3. Will let you know what happens

**Comment by sangeetds** [comment]
It's working now. Will try and see what could be the problem. Thanks for the help!
