### ISSUE TITLE
Examples/Tests for 0.2.0

### ISSUE THREAD

**Issue by markjfisher** [Kabbura/Kunafa#5]
I've just started using Kunafa, and struggling to find some concrete examples of usage.

The closest is the information in https://medium.com/the-kotlin-chronicle/kunafa-easy-to-use-high-level-framework-in-kotlin-for-front-end-web-development-ee5237aea5b but it doesn't link Component classes to a main, so I'm struggling to put them together. I'm sure it's obvious but I'm just missing it

I'd just like something fairly simple, so far I've created a simple Component class, as this:

    class AppView: Component() {
        override fun View?.getView(): View {
            return horizontalLayout {
                textView {
                    text = "Some text"
                }
            }
        }
    }

but how do I use it?
So far this is all I've managed:

    fun main(args: Array<String>) {
        page {
            AppView().addToParent(this)
        }
    }

which feels less than optimal.

I'd also ask, where are the tests? This is a large-ish code base for what it does but I don't see any tests anywhere. They were the first things I looked for in trying to work out how to get this going.

**Comment by Kabbura** [comment]
Hi
Here is a complete example for how to build an app. [Kunafa Todo App](https://github.com/Kabbura/Kunafa/wiki/Kunafa-Todo-App). 
To answer your question, call `mount()`

```kotlin
fun main(args: Array<String>) {
    page {
        mount(AppView())
    }
}
```
And yeah, the tests are not complete yet. We are working on completing the tests suite and publishing it.

**Comment by markjfisher** [comment]
Thank you so much for this! And the full working example.
This will really get me off the ground now. Cheers, I'll close this.
Hope to see those tests soon :)
