### ISSUE TITLE
Add custom HTML elements?

### ISSUE THREAD

**Issue by Sylvyrfysh** [Kabbura/Kunafa#8]
Is it possible with 0.2.4 to add a <span> in button text? I'm trying to create animated buttons and this is required, but I cannot figure out how to do it.

**Comment by Kabbura** [comment]
If I understand correctly, you want to set the body of the text to anchor element, correct? 
If that's so, you can simply set the a inside the button as such,
```kotlin
        button {
            a {
                href = "https://github.com/Kabbura/Kunafa/issues/8"
                text = "Issue #8"
            }
        }
```
This will generate 
```html
<button class="c-2"><a class="c-2" href="https://github.com/Kabbura/Kunafa/issues/8">Issue #8</a></button>
```
Feel free to close the issue if that's indeed what you need :)

**Comment by Sylvyrfysh** [comment]
That's in the right vain, but I specifically need spans, which I cannot seem to find. I'm trying to generate `<span>Button </span>`, which I can't figure out.

**Comment by Kabbura** [comment]
Yes you are right. Span currently isn't in Kuanfa. However, it is very easy to convert any HTML element to Kunafa component. For example, here is the code for the span.
```kotlin

class Span(parent: View? = null) : View(parent) {
    override val element: HTMLSpanElement = document.createElement("span") as HTMLSpanElement
}

fun View?.span(lifecycleObserver: LifecycleObserver? = null, block: Span.() -> Unit): Span = Span(this).visit(lifecycleObserver, block)
```
Then you can use it like any other Kunafa component
```kotlin
                span {
                    element.innerHTML = "Button"
                }
```

**Comment by Sylvyrfysh** [comment]
This works perfectly, thank you!
