### ISSUE TITLE
CSS 'content' tag is not sent to browser CSS if not escaped in code

### ISSUE THREAD

**Issue by Sylvyrfysh** [Kabbura/Kunafa#9]
Content tags are string tags. When the rules are turned into strings, they are not properly wrapped. This can be worked around by doing something like `RuleSet.content = "'Content'"`. Otherwise, the css sent will look like `content=Content`, which is a badly formed rule and will be dropped.

**Comment by Kabbura** [comment]
Spot on. 
Has been confirmed for the next release :+1:.

**Comment by Kabbura** [comment]
@Sylvyrfysh 
While working on this, I found that the content shouldn't always be escaped, for example when using CSS functions. Consider the following example: 
```kotlin
         a {
                text = "Hi &nbsp;"
                href = "http://narbase.com"
                style {
                    after {
                        content = "attr(href)"
                    }
                }
            }

```
Where the output should be `Hi  http://narbase.com` and not `Hi  attr(href)`.
What do you think?
